/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BackgroundConfig: typeof import('./src/components/BackgroundConfig/BackgroundConfig.vue')['default']
    BlurConfig: typeof import('./src/components/BlurConfig.vue')['default']
    BocchiOverlay: typeof import('./src/components/BocchiOverlay.vue')['default']
    Chip: typeof import('./src/components/Chip.vue')['default']
    ChipCard: typeof import('./src/components/ChipCard.vue')['default']
    ClientHome: typeof import('./src/components/ClientConfig/ClientHome.vue')['default']
    ConfigCard: typeof import('./src/components/ConfigCard.vue')['default']
    CustomColor: typeof import('./src/components/CustomColor/CustomColor.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    ImageInput: typeof import('./src/components/ImageInput.vue')['default']
    LogoConfig: typeof import('./src/components/LogoConfig.vue')['default']
    NColorPicker: typeof import('naive-ui')['NColorPicker']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NGradientText: typeof import('naive-ui')['NGradientText']
    NGrid: typeof import('naive-ui')['NGrid']
    NGridItem: typeof import('naive-ui')['NGridItem']
    NH1: typeof import('naive-ui')['NH1']
    NInputNumber: typeof import('naive-ui')['NInputNumber']
    NSelect: typeof import('naive-ui')['NSelect']
    NSlider: typeof import('naive-ui')['NSlider']
    NSpace: typeof import('naive-ui')['NSpace']
    NSpin: typeof import('naive-ui')['NSpin']
    NSwitch: typeof import('naive-ui')['NSwitch']
    NTag: typeof import('naive-ui')['NTag']
    NText: typeof import('naive-ui')['NText']
    NTooltip: typeof import('naive-ui')['NTooltip']
    PlayerConfig: typeof import('./src/components/PlayerConfig/PlayerConfig.vue')['default']
    Setting: typeof import('./src/components/SetupWizard/Setting.vue')['default']
    SetupComplete: typeof import('./src/components/SetupWizard/SetupComplete.vue')['default']
    SetupHome: typeof import('./src/components/SetupWizard/SetupHome.vue')['default']
    SetupRender: typeof import('./src/components/SetupWizard/SetupRender.vue')['default']
  }
}
